name: Alpha Build
on:
  push:
    branches:
      - alpha
jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16' ]
    name: Node ${{ matrix.node }} - Setup
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
  example-tests:
    runs-on: ubuntu-latest
    needs: [setup]
    strategy:
      matrix:
        node: [ '14', '16' ]
    name: Node ${{ matrix.node }} - Example Test
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm run install:example
      - run: npm run test:example
  test:
    runs-on: ubuntu-latest
    needs: [setup]
    strategy:
      matrix:
        node: [ '14', '16' ]
    name: Node ${{ matrix.node }} - Test
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npm run test:cover
  publish:
    runs-on: ubuntu-latest
    name: Versionning and Publish
    needs: [example-tests, test]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npm run test:example
      - run: npm run test:cover
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
